miner_db_mode = { Live = 0 }
miner_api_port = 3001

user_db_mode = { Live = 0 }
user_api_port = 3001

[[mempool_nodes]]
# testnet
address = "34.65.95.17:8116"
# mainnet
# address = "34.65.95.17:8333"

[[miner_nodes]]
address = "127.0.0.1:12341"

[[user_nodes]]
address = "127.0.0.1:12351"
