version: '3'
services:
  miner-0:
    image: ghcr.io/aiblockofficial/node-miner:latest
    ports:
    - '12340:12340'
    - '12350:12350'
    - '3000:3000'
    volumes:  
    - /tmp/miner-0:/src
    - ./node_settings.toml:/etc/node_settings.toml
    command: miner
    environment:
    - WITH_USER_INDEX=0
    - RUST_LOG=info,debug
    ### uncomment for Linux
    #user: "${UID}:${GID}"