version: '3'
services:
  miner-0:
    image: ghcr.io/aiblockofficial/node-miner:sha-1c5898f
    ports:
    - '12341:12341'
    - '12351:12351'
    - '3000:3000'
    - '3001:3001'
    volumes:  
    - ./ai_block/miner:/src
    - ./node_settings.toml:/etc/node_settings.toml
    command: miner
    environment:
    - RUST_LOG=info,debug
    - WITH_USER_INDEX=0
    - ADDRESS_AGGREGATION_LIMIT=999
    ## Uncomment the following line if running Linux
    user: "${UID}:${GID}"